name: Jeremy Sarber
favicon: null
layout_spectrum: 0.9005174213089049
typography_spectrum: 1
title: Jeremy Sarber
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#211715'
    - '#4c5d31'
    - '#a66d5a'
    - '#f7bfab'
  brandStrength: 0.5
  lightness: 0.3662180188111961
  saturation: 1
  rhythmicContrast: 0.25302129285410047
purpose: []
