name: Jeremy Sarber
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Jeremy Sarber
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090401'
    - '#e0cdbc'
    - '#b98e64'
    - '#816e5d'
    - '#3c618b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
